import { useState, useRef } from "react";
import { Upload, FileJson, AlertTriangle, CheckCircle } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/services/database";

const AdminDataImport = () => {
  const [importData, setImportData] = useState<Record<string, any[]> | null>(null);
  const [isImporting, setIsImporting] = useState(false);
  const [importResults, setImportResults] = useState<{ table: string; count: number; status: "success" | "error"; message?: string }[]>([]);
  const fileRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const data = JSON.parse(event.target?.result as string);
        setImportData(data);
        setImportResults([]);
      } catch {
        toast({ title: "Invalid file", description: "Please upload a valid JSON file.", variant: "destructive" });
      }
    };
    reader.readAsText(file);
  };

  const handleImport = async () => {
    if (!importData) return;
    setIsImporting(true);
    const results: typeof importResults = [];

    for (const [table, records] of Object.entries(importData)) {
      if (!Array.isArray(records) || records.length === 0) continue;
      try {
        const { error } = await supabase.from(table as any).upsert(records as any, { onConflict: "id" });
        results.push({
          table,
          count: records.length,
          status: error ? "error" : "success",
          message: error?.message,
        });
      } catch (err: any) {
        results.push({ table, count: records.length, status: "error", message: err.message });
      }
    }

    setImportResults(results);
    setIsImporting(false);
    const successCount = results.filter(r => r.status === "success").length;
    toast({ title: "Import complete", description: `${successCount}/${results.length} tables imported successfully.` });
  };

  return (
    <div className="space-y-4">
      <div>
        <h2 className="text-2xl font-bold text-foreground font-display">Data Import Tools</h2>
        <p className="text-muted-foreground text-sm mt-1">Import data from JSON backup files.</p>
      </div>

      <Card>
        <CardContent className="p-6 text-center space-y-4">
          <div className="w-16 h-16 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto">
            <Upload className="w-8 h-8 text-primary" />
          </div>
          <div>
            <p className="text-sm font-medium text-foreground">Upload a JSON backup file</p>
            <p className="text-xs text-muted-foreground mt-1">Supports backup files generated by the Export or Backup tools</p>
          </div>
          <input type="file" accept=".json" ref={fileRef} className="hidden" onChange={handleFileSelect} />
          <Button variant="outline" onClick={() => fileRef.current?.click()}>
            <FileJson className="w-4 h-4 mr-1" /> Select File
          </Button>
        </CardContent>
      </Card>

      {importData && (
        <Card>
          <CardContent className="p-4 space-y-3">
            <p className="text-sm font-medium text-foreground">Preview:</p>
            <div className="space-y-1">
              {Object.entries(importData).map(([table, records]) => (
                <div key={table} className="flex items-center justify-between text-sm p-2 rounded-lg bg-muted/50">
                  <span className="font-medium text-foreground">{table}</span>
                  <span className="text-muted-foreground">{Array.isArray(records) ? records.length : 0} records</span>
                </div>
              ))}
            </div>
            <div className="flex items-center gap-2 p-3 rounded-lg bg-yellow-500/10 border border-yellow-500/20">
              <AlertTriangle className="w-4 h-4 text-yellow-500 flex-shrink-0" />
              <p className="text-xs text-yellow-600 dark:text-yellow-400">Import will upsert data. Existing records with matching IDs will be overwritten.</p>
            </div>
            <Button onClick={handleImport} disabled={isImporting}>
              <Upload className="w-4 h-4 mr-1" /> {isImporting ? "Importing..." : "Start Import"}
            </Button>
          </CardContent>
        </Card>
      )}

      {importResults.length > 0 && (
        <Card>
          <CardContent className="p-4 space-y-2">
            <p className="text-sm font-medium text-foreground">Import Results:</p>
            {importResults.map((result) => (
              <div key={result.table} className="flex items-center gap-2 text-sm">
                {result.status === "success" ? <CheckCircle className="w-4 h-4 text-green-500" /> : <AlertTriangle className="w-4 h-4 text-red-500" />}
                <span className="font-medium">{result.table}</span>
                <span className="text-muted-foreground">({result.count} records)</span>
                {result.message && <span className="text-xs text-red-500">{result.message}</span>}
              </div>
            ))}
          </CardContent>
        </Card>
      )}
    </div>
  );
};

export default AdminDataImport;
